# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(default='test entry', max_length=200),
            preserve_default=False,
        ),
    ]
