# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_auto_20160411_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='processed',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
