# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0004_journalentry_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='author',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
