# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0007_processedentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='processedentry',
            name='entry',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='ProcessedEntry',
        ),
    ]
