# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0011_journalentry_processedentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rf_token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sp_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
